web/router.ex
defmodule PuppetdbFrontend.Router do
  use Phoenix.Router

  pipeline :browser do
    plug :accepts, ~w(html)
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
  end

  pipeline :api do
    plug :accepts, ~w(json)
  end

  scope "/", PuppetdbFrontend do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/nodes", NodesController, only: [:index, :show]
  end

  # Other scopes may use custom stacks.
  # scope "/api", PuppetdbFrontend do
  #   pipe_through :api
  # end
end

lib/puppetdb_frontend/endpoint.ex
defmodule PuppetdbFrontend.Endpoint do
  use Phoenix.Endpoint, otp_app: :puppetdb_frontend

  # Serve at "/" the given assets from "priv/static" directory
  plug Plug.Static,
    at: "/", from: :puppetdb_frontend,
    only: ~w(css images js favicon.ico robots.txt)

  plug Plug.Logger

  # Code reloading will only work if the :code_reloader key of
  # the :phoenix application is set to true in your config file.
  plug Phoenix.CodeReloader

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  plug Plug.Session,
    store: :cookie,
    key: "_puppetdb_frontend_key",
    signing_salt: "45GU1T1w",
    encryption_salt: "np/auFxN"

  plug :router, PuppetdbFrontend.Router
end

web/controllers/nodes_controller.ex
defmodule PuppetdbFrontend.NodesController do
  use Phoenix.Controller

  plug :action

  def index(conn, _params) do
    render conn, "index.html"
  end

  def show(conn, %{"id" => id}) do
    render conn, "show.html", id: id
  end
end

web/controllers/page_controller.ex
defmodule PuppetdbFrontend.PageController do
  use Phoenix.Controller

  plug :action

  def index(conn, _params) do
    render conn, "index.html"
  end
end

web/views/error_view.ex
defmodule PuppetdbFrontend.ErrorView do
  use PuppetdbFrontend.View

  def render("404.html", _assigns) do
    "Page not found - 404"
  end

  def render("500.html", _assigns) do
    "Server internal error - 500"
  end

  # Render all other templates as 500
  def render(_, assigns) do
    render "500.html", assigns
  end
end

web/views/layout_view.ex
defmodule PuppetdbFrontend.LayoutView do
  use PuppetdbFrontend.View
end

web/views/nodes_view.ex
defmodule PuppetdbFrontend.NodesView do
  use PuppetdbFrontend.View

  def nodes do
    PuppetDB.nodes.body
  end

  def nodes(name) do
    PuppetDB.nodes(name).body
  end

  def facts(name) do
    PuppetDB.facts(name).body
  end
end

web/views/page_view.ex
defmodule PuppetdbFrontend.PageView do
  use PuppetdbFrontend.View
end

web/templates/layout/application.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>PuppetDB Frontend</title>
    <link rel="stylesheet" href="/css/phoenix.css">
    <script src="http://www.kryogenix.org/code/browser/sorttable/sorttable.js"></script>
  </head>

  <body>
    <div class="container">
      <%= @inner %>
    </div> <!-- /container -->
  </body>
</html>

web/templates/nodes/index.html.eex
<h2>Nodes</h2>

<table class="table sortable">
  <tr>
    <th>Name</th>
    <th>Catalog</th>
    <th>Deactivated</th>
    <th>Facts</th>
    <th>Report</th>
  </tr>

  <%= for node <- nodes do %>
  <tr>
    <td><a href="<%= nodes_path(Endpoint, :show, node["name"]) %>"><%= node["name"] %></a></td>
    <td><%= node["catalog_timestamp"] %></td>
    <td><%= node["deactivated"] %></td>
    <td><%= node["facts_timestamp"] %></td>
    <td><%= node["report_timestamp"] %></td>
  </tr>
  <% end %>
</table>

web/templates/nodes/show.html.eex
<h2><%= nodes(@id)["name"] %></h2>

<p>
  <a class="btn btn-default" href="/nodes">Back</a>
</p>

Name: <b><%= nodes(@id)["name"] %></b><br>
Catalog Timestamp: <b><%= nodes(@id)["catalog_timestamp"] %></b><br>
Deactivated: <b><%= nodes(@id)["deactivated"] %></b><br>
Facts Timestamp: <b><%= nodes(@id)["facts_timestamp"] %></b><br>
Report Timestamp: <b><%= nodes(@id)["report_timestamp"] %></b><br>

<h3>Facts</h3>

<table class="table table-condensed sortable">
  <tr>
    <th>Name</th>
    <th>Value</th>
  </tr>

<%= for fact <- facts(@id) do %>
  <tr>
    <td><%= fact["name"] %></td>
    <td><%= fact["value"] %></td>
  </tr>
<% end %>
</table>

web/templates/page/error.html.eex
Something went wrong

web/templates/page/index.html.eex
<div class="jumbotron">
  <h2>Welcome to Phoenix!</h2>
  <p class="lead">Phoenix is an Elixir Web Framework targeting full-featured, fault tolerant applications with realtime functionality.</p>
</div>

<div class="row marketing">
  <div class="col-lg-6">
    <h4>Resources</h4>
    <ul>
      <li>
        <a href="http://hexdocs.pm/phoenix">Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
    </ul>
  </div>

  <div class="col-lg-6">
    <h4>Help</h4>
    <ul>
      <li>
        <a href="https://github.com/phoenixframework/phoenix/issues?state=open">Issues</a>
      </li>
      <li>
        <a href="irc://irc.freenode.net/elixir-lang">#elixir-lang on freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/chris_mccord">@chris_mccord</a>
      </li>
    </ul>
  </div>
</div>

web/templates/page/not_found.html.eex
The page you are looking for does not exist